### ISSUE TITLE
Add sentence/pattern similarity metric to module lexical-asl

### ISSUE THREAD

**Issue by nicolaierbs** [dkpro/dkpro-similarity#34]
Original [issue 34](https://code.google.com/p/dkpro-similarity-asl/issues/detail?id=34) created by dkpro on 2014-11-21T08:44:14.000Z:

Add the sentence/pattern similarity metric used in the paper

Automated Verb Sense Labelling Based on Linked Lexical Resources
Kostadin Cholakov and Judith Eckle-Kohler and Iryna Gurevych
In: Proceedings of the 14th Conference of the European Chapter of the Association for Computational Linguistics (EACL 2014), p. 68-77, Association for Computational Linguistics, April 2014. 

to lexical-asl

**Comment by judithek** [comment]
citing 2014 comments from Torsten here (translated):

This metric would fit into the module lexical-asl, where Jaccard and Containment are already available.
Dice should require just a small change (is 2*Jaccard).
Maybe do some refactoring, i.e. base class instead of override.

the weighted combination of ngrams across different levels (lemma, POS, token) is also applicable in a generic way. Therefore it might be better to create a wrapper-similarity class which then can be used for other ngram-based similarity measures as well.
Something like:
new WeightedCombinationMeasure(new WordNgramDiceMeasure(), 2, 3, 4)

**Comment by zesch** [comment]
If there is a need for this measure, please re-open.
